config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/about', to: 'static_pages#about'

  resources :parts
end


# Rails.application.routes.draw do

#   get 'static_pages/home'
#   get 'static_pages/about'

#   resources :parts #this almost killed me
  
#   #this automatically includes all basic crud routes for parts
# end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/part.rb
class Part < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  
  #read all pages
  def index
    @parts = Part.all 
  end

  #Finds a page by the id passed in
  def show
    @parts = Part.find(params[:id])
  end

  #Creates a new page in memory that is not yet saved to the db
  def new
    @parts = Part.new
  end

  def create 
    @parts = Part.new(parts_params)

    if @parts.save
      redirect_to parts_path(@parts.id)
    else
      render :new
    end
  end

  def edit
    @parts = Part.find(params[:id])
  end

  def update
    @parts = Part.find(params[:id])
  
    if @parts.update(parts_params)
      redirect_to parts_path
    else
      render :edit
    end
  end

  def destroy
    Part.find(params[:id]).destroy
    redirect_to parts_path
  end

  private

  def parts_params
    params.require(:part).permit(:name, :color, :description, :manufacturer)
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>
<%= link_to 'Parts', parts_path %>
<%= link_to 'New Part', new_part_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bike</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/parts/edit.html.erb
<h1>Edit Part</h1>
<%= form_for @parts do |f| %>
  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :color %>
  <%= f.text_field :color %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :manufacturer %>
  <%= f.text_field :manufacturer %>

  <%= f.submit %>
<% end %>

app/views/parts/index.html.erb
<h1>Parts</h1>
<% @parts.each do |part| %>
  <h2><%= part.name %></h2>  
  <%= link_to 'New Part', new_part_path %>
  <%= link_to 'Show Part', part_path(part) %>
  <%= link_to 'Edit Part', edit_part_path(part) %>
  <%= link_to 'Destroy Part', part, method: :delete %>

<% end %>

app/views/parts/new.html.erb
<h1>New Part</h1>
<%= form_for @parts do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :color %>
  <%= f.text_field :color %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :manufacturer %>
  <%= f.text_field :manufacturer %>

  <%= f.submit %>
<% end %>

app/views/parts/show.html.erb
<h1><%= @parts.name %></h1>
<h1><%= @parts.color %></h1>
<h1><%= @parts.description %></h1>
<h1><%= @parts.manufacturer %></h1>
<%= link_to 'Back', parts_path %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>